language: cpp

os:
  - linux
  - osx

compiler:
  - clang
  - gcc

env:
  matrix:
    - BUILD_TYPE=Debug   CFLAGS=-m32 CXXFLAGS=-m32
    - BUILD_TYPE=Debug   CFLAGS=-m64 CXXFLAGS=-m64
    - BUILD_TYPE=Release CFLAGS=-m32 CXXFLAGS=-m32
    - BUILD_TYPE=Release CFLAGS=-m64 CXXFLAGS=-m64

matrix:
  exclude:
    - os: osx
      compiler: gcc

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
         CMAKE_PACKAGE="cmake-3.3.2-Linux-x86_64"
      && wget https://www.cmake.org/files/v3.3/${CMAKE_PACKAGE}.tar.gz --no-check-certificate
      && sudo apt-get -qq update
      && sudo apt-get -qq install gcc-multilib g++-multilib valgrind
      && tar -xzf ${CMAKE_PACKAGE}.tar.gz
      && sudo cp -fR ${CMAKE_PACKAGE}/* /usr
      ;
    else
         brew update
      && brew unlink cmake
      && brew install -v cmake
      ;
    fi

before_script:
  - mkdir build
  - cd build
  - cmake --version
  - cmake .. -G"Unix Makefiles" -DCMAKE_BUILD_TYPE="$BUILD_TYPE" -DASMJIT_BUILD_TEST=1
  - cd ..

script:
  - cd build
  - make
  - cd ..

  - ./build/asmjit_test_unit
  - ./build/asmjit_test_x86

after_success:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then valgrind --leak-check=full --show-reachable=yes ./build/asmjit_test_unit; fi;
